# Taps
tap "homebrew/autoupdate"
tap "oven-sh/bun"

# Quick Look Plugins
cask "provisionql"
cask "suspicious-package"
cask "syntax-highlight"
cask "quicklook-json"
cask "quicklookase"
cask "qlvideo"
cask "webpquicklook"

# Fonts
cask "font-fira-code"
cask "font-hack"
cask "font-ibm-plex"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-monaspace"
cask "font-source-code-pro"

# Accessibility
cask "betterdisplay"
cask "monitorcontrol"
cask "rectangle"

# CLI
brew "ffmpeg"
brew "mas"
brew "jq"
brew "rclone"
brew "tree"
brew "wget"
brew "xz"
brew "yq"
brew "yt-dlp"
brew "zsh"
brew "zsh-completions"

# Apps
cask "appcleaner"
cask "obsidian"
cask "onyx"
cask "sublime-text"
cask "the-unarchiver"
cask "warp"

# Browsers
cask "brave-browser"
cask "google-chrome"
cask "firefox"

# Development
brew "awscli"
brew "bun"
cask "docker"
brew "deno"
brew "git"
brew "gh"
brew "go"
cask "insomnia"
cask "lm-studio"
brew "node"
cask "ngrok"
brew "pnpm"
brew "python"
brew "rust"
brew "uv"
cask "visual-studio-code"

# App Store Apps
mas "Xcode", id: 497799835
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
