#!/usr/bin/env zsh

# Checks a SvelteKit project for gaps, quality, security and performance → docs/CHECK.md
# Run from the project root. Exits 1 when a ❌ check fails, so it can gate CI.

set -uo pipefail
zmodload zsh/datetime

# Log Functions
info() { echo "\033[0;34mℹ️  $*\033[0m"; }
warn() { echo "\033[0;33m⚠️  $*\033[0m"; }
error() { echo "\033[0;31m❌ $*\033[0m"; }
success() { echo "\033[0;32m✅ $*\033[0m"; }

# Helper Functions
installed() { [[ -n $(pnpm pkg get "devDependencies[\"$1\"]") ]]; }
has_script() { [[ -n $(pnpm pkg get "scripts[\"$1\"]") ]]; }
kb() { printf '%.1f KB' $(($1 / 1024.0)); }

# check <mark on failure> <title> <cmd...>: runs cmd, records its result and output tail
check() {
  local mark=$1 title=$2 out rc
  shift 2
  info "$title..."
  out=$("$@" 2>&1)
  rc=$?
  ((rc)) && [[ $mark == ❌ ]] && ((fails++))
  summary+=("| $title | $( ((rc)) && echo $mark || echo ✅) |")
  details+=("### $title" "" '```' "$(print -r -- "${out:-(no output)}" | sed $'s/\e\\[[0-9;]*m//g' | tail -n 60)" '```' "")
  return $rc
}

# table <heading> <col> <col> <rows...>: markdown table section, skipped when there are no rows
table() {
  (($# > 3)) || return 0
  print -rl -- "" "$1" "" "| $2 | $3 |" "| --- | --- |" "${@:4}"
}

# Checks
installed @sveltejs/kit || {
  error "Not a SvelteKit project"
  exit 1
}

report=docs/CHECK.md tmp=$(mktemp -d) port=4173
summary=() gaps=() perf=() largest=() scores=() vitals=() details=() fails=0
trap 'kill ${preview:-} 2>/dev/null; rm -rf $tmp' EXIT
export NO_COLOR=1 FORCE_COLOR=0

# Gaps
info "Checking for gaps..."
files=(
  README.md .env.example
  docs/README.md docs/CONTRIBUTING.md docs/SECURITY.md
  .github/workflows/ci.yml
  src/routes/+error.svelte
  static/robots.txt static/sitemap.xml static/manifest.json static/humans.txt
)
[[ $(pnpm pkg get private) == true ]] || files+=(LICENSE)
for f in $files; do [[ -e $f ]] || gaps+=("- Missing \`$f\`"); done
for k in description homepage repository.url; do
  [[ $(pnpm pkg get $k) == (|'""') ]] && gaps+=("- \`package.json\` → \`$k\` is empty")
done
grep -qs yourdomain.com static/{robots.txt,sitemap.xml} && gaps+=("- Placeholder \`yourdomain.com\` in robots.txt / sitemap.xml")
installed vitest || gaps+=("- No unit tests (vitest)")
installed @playwright/test || gaps+=("- No e2e tests (playwright)")
summary+=("| Gaps | $( (($#gaps)) && echo "⚠️ $#gaps found" || echo ✅) |")

# Quality
has_script check && check ❌ "Type check" pnpm check
has_script lint && check ❌ "Lint" pnpm lint
has_script test && check ❌ "Tests" pnpm test
check ⚠️ "Unused files, exports & deps (knip)" pnpm dlx knip --no-progress

# Security
# https://osv.dev
if (($+commands[osv - scanner])); then
  check ❌ "Vulnerabilities (osv-scanner)" osv-scanner scan -L pnpm-lock.yaml
else
  check ❌ "Vulnerabilities (pnpm audit)" pnpm audit
fi
check ⚠️ "Outdated dependencies" pnpm outdated

# Performance
start=$EPOCHREALTIME
if check ❌ "Build" pnpm build; then
  perf+=("| Build time | $(printf %.1f $((EPOCHREALTIME - start)))s |")

  # Bundle size, gzipped per file like the browser receives it
  client=.svelte-kit/output/client
  for ext in js css; do
    assets=($client/**/*.$ext(N.))
    raw=0 gz=0
    for f in $assets; do ((raw += $(wc -c <$f), gz += $(gzip -9c $f | wc -c))); done
    perf+=("| Client ${ext:u} | $(kb $raw) ($(kb $gz) gzip, $#assets files) |")
  done
  for f in $client/**/*.(js|css)(N.OL[1,5]); do largest+=("| \`${f#$client/}\` | $(kb $(wc -c <$f)) |"); done

  # Lighthouse (mobile, simulated throttling) against `vite preview`
  # https://github.com/GoogleChrome/lighthouse
  ./node_modules/.bin/vite preview --port $port --strictPort >/dev/null 2>&1 &
  preview=$!
  for i in {1..30}; do curl -sf localhost:$port >/dev/null && break || sleep 1; done
  if check ⚠️ "Lighthouse" pnpm dlx lighthouse http://localhost:$port \
    --quiet --chrome-flags=--headless=new --output=json --output-path=$tmp/lh.json; then
    scores=(${(f)"$(jq -r '.categories[] | "| \(.title) | \((.score // 0) * 100 | round) |"' $tmp/lh.json)"})
    vitals=(${(f)"$(jq -r '.audits as $a
      | ["first-contentful-paint", "largest-contentful-paint", "total-blocking-time", "cumulative-layout-shift", "speed-index"][]
      | "| \($a[.].title) | \($a[.].displayValue) |"' $tmp/lh.json)"})
  fi
fi

# Report
mkdir -p docs
{
  print -r "# Project Check"
  print -rl -- "" "> \`$(pnpm pkg get name)@$(pnpm pkg get version)\` · generated by \`sv-check\` on $(date '+%Y-%m-%d %H:%M')"
  table "## Summary" Check Result $summary
  print -rl -- "" "## Gaps" "" ${gaps:-None.}
  table "## Performance" Metric Value $perf
  table "### Largest client assets" File Size $largest
  table "### Lighthouse (mobile)" Category Score $scores
  table "### Web vitals" Metric Value $vitals
  print -rl -- "" "## Details" "" $details
} >$report

success "Report written to $report"
((fails)) && {
  error "$fails check(s) failed"
  exit 1
}
exit 0
